### ISSUE TITLE
AAAA/IPv6

### ISSUE THREAD

**Issue by kimboslice99** [fire1ce/DDNS-Cloudflare-PowerShell#2]
What changes would need to be made for this script to be used on IPv6/AAAA records?

working for IPv4 but not IPv6... already changed 
```
"type"    = "A"
``` 
to 
```
"type"    = "AAAA"
```
and using https://ip6.seeip.org to get external ipv6 address... working great for IPv4 addresses, though, thanks!

Edit; scratch that, not working on IPv4 now either... getting 405 Method not allowed

**Comment by bobdig** [comment]
I also would appreciate a script for IPv6

**Comment by fire1ce** [comment]
@kimboslice99, @bobdig 
The script's core was written for IPv4. Small changes won't do to make it work with IPv6. 
I've added a Limitations section at readme declaring the lack  of IPv6 support.
I'm not going to add the functionality since i don't have use for it. 
You are always welcome to send Pull requests if you add it. 

Have a great day.

**Comment by Jack-Works** [comment]
See https://github.com/fire1ce/DDNS-Cloudflare-PowerShell/pull/8
